language: node_js
node_js: stable

script:
  - npm run publish

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs
  target_branch: gh-pages
  edge: true
  on:
    branch: master
