export default {
  speed:
    { "NavigationBarColor": "#182c3b", "NavigationBarTextColor": "#FFFFFF", "TabBarColor": "#F6F6F6", "TabBarBorderColor": "#EDEDED", "TabBarSelectedColor": "#e61d57", "TabBarUnselectedColor": "#8f8f8f", "TableBackgroundColor": "#F5F5F5", "TableCellBackgroundColor": "#FFFFFF", "TableSeparatorColor": "#ffffff", "TextLabelTextColor": "#000000", "DetailLabelTextColor": "#C9C9C9", "ButtonIconColor": "#4de0a8", "ButtonNormalColor": "#f64252", "PingSuccessTextColor": "#59A46F", "PingTimeoutTextColor": "#DA7D72", "DefaultDotColor": "#44a2c9" },
  boxyuk:
    { "NavigationBarColor": "#293e51", "NavigationBarTextColor": "#ffffff", "TabBarColor": "#F6F6F6", "TabBarBorderColor": "#EDEDED", "TabBarSelectedColor": "#e68728", "TabBarUnselectedColor": "#828282", "TableBackgroundColor": "#F5F5F5", "TableCellBackgroundColor": "#FFFFFF", "TableSeparatorColor": "#ffffff", "TextLabelTextColor": "#013c56", "DetailLabelTextColor": "#C9C9C9", "ButtonIconColor": "#e68728", "ButtonNormalColor": "#FFFFFF", "PingSuccessTextColor": "#59A46F", "PingTimeoutTextColor": "#DA7D72", "DefaultDotColor": "#FD9502" },
  chocolate:
    { "NavigationBarColor": "#201a1a", "NavigationBarTextColor": "#ffffff", "TabBarColor": "#201a1a", "TabBarBorderColor": "#c65d75", "TabBarSelectedColor": "#c65d75", "TabBarUnselectedColor": "#828282", "TableBackgroundColor": "#201a1a", "TableCellBackgroundColor": "#2b2223", "TableSeparatorColor": "#000000", "TextLabelTextColor": "#dddfe2", "DetailLabelTextColor": "#C9C9C9", "ButtonIconColor": "#c65d75", "ButtonNormalColor": "#ffffff", "PingSuccessTextColor": "#7a9c52", "PingTimeoutTextColor": "#DA7D72", "DefaultDotColor": "#6fa198" },
  bilibili:
    { "NavigationBarColor": "#fb7299", "NavigationBarTextColor": "#ffffff", "TabBarColor": "#F6F6F6", "TabBarBorderColor": "#e7e7e7", "TabBarSelectedColor": "#ff5c7c", "TabBarUnselectedColor": "#8f8f8f", "TableBackgroundColor": "#f5f5f5", "TableCellBackgroundColor": "#FFFFFF", "TableSeparatorColor": "#ffffff", "TextLabelTextColor": "#0090bf", "DetailLabelTextColor": "#81d5f0", "ButtonIconColor": "#ff5c7c", "ButtonNormalColor": "#ffdd80", "PingSuccessTextColor": "#47b01b", "PingTimeoutTextColor": "#fb7299", "DefaultDotColor": "#fcba2a" },
  oldSchool:
    { "NavigationBarColor": "#ffffff", "NavigationBarTextColor": "#1a1a1a", "TabBarColor": "#ffffff", "TabBarBorderColor": "#6ecfcf", "TabBarSelectedColor": "#1d74be", "TabBarUnselectedColor": "#b0b0b0", "TableBackgroundColor": "#F5F5F5", "TableCellBackgroundColor": "#FFFFFF", "TableSeparatorColor": "#6ecfcf", "TextLabelTextColor": "#3f3f3f", "DetailLabelTextColor": "#C9C9C9", "ButtonIconColor": "#1D74BE", "ButtonNormalColor": "#1d74be", "PingSuccessTextColor": "#59A46F", "PingTimeoutTextColor": "#DA7D72", "DefaultDotColor": "#FD9502" }
}
